version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"  # Optional: expose Redis port if you want host access

  fastapi:
    build:
      context: .  # Assumes your Dockerfile is in the root of the project
    container_name: taskapi-container
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
